name: Deploy App (Dev)

on:
  push:
    branches:
      - main
    paths:
      - src/app/**
      - .github/workflows/app.yml
      - .github/workflows/app_dev.yml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Deploy App to Dev
    uses: ./.github/workflows/app.yml
    with:
      environment: Dev
    secrets: inherit
